spring:
  datasource:
    url: jdbc:h2:tcp://localhost/./testdb
    username: testdb
    password: test
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
jwt:
  key: testtesttesttesttesttesttesttesttesttesttesttesttesttesttesttest
  expiration-seconds: 604800