spring:
  datasource:
    url: jdbc:h2:tcp://localhost/./testdb
    username: testdb
    password: test
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database: h2
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
jwt:
  key: testtesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttest
  expiration-seconds: 604800
logging:
  level:
    org.springframework.security: DEBUG
server:
  error:
    include-message: always