spring:
  datasource:
    url: jdbc:h2:tcp://localhost/./testdb
    username: testdb
    password: test
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
jwt:
  key: testtesttesttesttesttesttesttesttesttesttesttesttesttesttesttest
  expiration-seconds: 604800